"use client";

import { useState } from "react";

interface CreateOutputProps {
  draft: string;
  contentType: string;
  brief: string;
  onSendToBarRaiser: (data: {
    draft: string;
    contentType: string;
    context: string;
  }) => void;
}

export default function CreateOutput({
  draft,
  contentType,
  brief,
  onSendToBarRaiser,
}: CreateOutputProps) {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(draft);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleSendToBarRaiser = () => {
    onSendToBarRaiser({
      draft,
      contentType,
      context: `This draft was generated by AACM based on the following brief: ${brief}`,
    });
  };

  return (
    <div className="rounded-lg border border-border bg-surface">
      {/* Header */}
      <div className="flex items-center justify-between border-b border-border px-6 py-4">
        <h2 className="text-sm font-semibold uppercase tracking-widest text-text-muted">
          Generated Draft
        </h2>
        <div className="flex items-center gap-2">
          <button
            onClick={handleCopy}
            className="rounded-md border border-border px-3 py-1.5 text-xs font-medium text-text-secondary transition-colors hover:bg-surface-light hover:text-text-primary"
          >
            {copied ? "Copied!" : "Copy Draft"}
          </button>
          <button
            onClick={handleSendToBarRaiser}
            className="rounded-md bg-accent px-3 py-1.5 text-xs font-medium text-white transition-colors hover:bg-accent-hover"
          >
            Send to Bar Raiser
          </button>
        </div>
      </div>

      {/* Draft content */}
      <div className="px-6 py-5">
        <div className="prose prose-sm max-w-none">
          {draft.split("\n").map((line, i) => {
            if (!line.trim()) return <br key={i} />;

            // Headers
            if (line.startsWith("# ")) {
              return (
                <h1
                  key={i}
                  className="text-xl font-bold text-text-primary mt-4 mb-2"
                >
                  {line.replace(/^#\s+/, "")}
                </h1>
              );
            }
            if (line.startsWith("## ")) {
              return (
                <h2
                  key={i}
                  className="text-lg font-bold text-text-primary mt-4 mb-2"
                >
                  {line.replace(/^##\s+/, "")}
                </h2>
              );
            }
            if (line.startsWith("### ")) {
              return (
                <h3
                  key={i}
                  className="text-base font-semibold text-text-primary mt-3 mb-1"
                >
                  {line.replace(/^###\s+/, "")}
                </h3>
              );
            }

            // Assumptions section
            if (/^ASSUMPTIONS MADE/i.test(line.trim())) {
              return (
                <p
                  key={i}
                  className="font-bold text-accent mt-5 mb-2 text-xs uppercase tracking-widest"
                >
                  {line}
                </p>
              );
            }

            return (
              <p
                key={i}
                className="text-text-secondary text-sm leading-relaxed mb-2"
              >
                {line}
              </p>
            );
          })}
        </div>
      </div>
    </div>
  );
}
